### ISSUE TITLE
Install include task fails

### ISSUE THREAD

**Issue by NesManrique** [bertvv/ansible-role-dhcp#10]
Hello!

I was using this in a redhat flavored linux (oracle linux) and found that the role dies in this task:

TASK [dhcp : Install includes] *************************************************
task path: /root/ovm_scripts/ansible/ovm_roles/opt/dhcp/tasks/main.yml:22
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "'dhcp_global_includes' is undefined"
}

It seems you are trying to shortcircuit `with_items` with `when`.  As [the docs](http://docs.ansible.com/ansible/playbooks_conditionals.html#loops-and-conditionals) state, the correct form here is to use the default([]) filter to return an empty list, which will skip the task.

Thank you!

**Comment by bertvv** [comment]
Thanks for reporting this. Should be fixed in b807e30 (v2.1.1)
