### ISSUE TITLE
Add support for fixed address hosts in subnets

### ISSUE THREAD

**Issue by asghaier** [bertvv/ansible-role-dhcp#13]
It is not possible to use fixed address hosts in subnets.
It would be nice if the same existing behaviour to add dhcp_hosts option would be also possible in subnets.

**Comment by jfarcher** [comment]
This doesn't seem to be working... 

> dhcp_subnets:
>       - ip: 192.168.1.0
>         netmask: 255.255.255.0
>         domain_name_servers: 192.168.1.1
>         range_begin: 192.168.1.151
>         range_end: 192.168.1.200
>         routers: 192.168.1.1
>         hosts:
>           - name: node1
>             mac: '00:1a:4a:16:01:39'
>             ip: 192.168.1.133

Creates the dhcpd.conf with the relevant subnet declaration but no fixed hosts

**Comment by jfarcher** [comment]
Ignore that comment, i was working from the syntax in your test file which is different than specified in the wiki. I changed hosts to dhcp_hosts and all is now good.

**Comment by blofeldthefish** [comment]
@asghaier  belated thanks for your contribution!!
