### ISSUE TITLE
Please create a new release with 2.2.0 version for ansible galaxy

### ISSUE THREAD

**Issue by sseide** [bertvv/ansible-role-dhcp#20]
Currently the latest version seen by ansible-galaxy is 2.1.2. Please create a new release with the 2.2.0 version to be able to install from galaxy.

Thanks,
Stefan

**Comment by bertvv** [comment]
Sorry for the wauit, but I'm working on it as we speak... It'll be 3.0.0 as the new release contains breaking changes. I'll close this bug after the release.

**Comment by bertvv** [comment]
v2.2.0 was released on Ansible Galaxy, v3.0.0 is coming shortly

See https://galaxy.ansible.com/bertvv/dhcp
