### ISSUE TITLE
Need to define network device in /etc/defaults

### ISSUE THREAD

**Issue by mok0** [bertvv/ansible-role-dhcp#21]
When using this role to make a fresh install of isc-dhcp-server on raspian (stretch) I found that dhcpd failed when it was first started.

The reason is that /etc/init.d/isc-dhcp-server wants to know on which network device the server must listen. In my case I had to edit the `/etc/defaults/isc-dhcp-server` file to contain the following:

`INTERFACESv4="eth0"`

because I want the server to listen to the wired ethernet device. I did that with a `lineinfile` Ansible command, but ideally, it should be done before starting the server the first time, but after installing the isc-dhcp-server package.

**Comment by bertvv** [comment]
Should be fixed by PR #25. I'm closing this issue for now. Can you test with the new version of this role, when it is released? Thank you for reporting this!
