### ISSUE TITLE
Make interfaces configurable

### ISSUE THREAD

**Issue by detcoGbR** [bertvv/ansible-role-dhcp#34]
Hi,
this is a follow up to #25, I need the interfaces to be configurable.
I am deploying to a multihomed host, which should provide dhcp on two of its four network cards, but not on it's default card (ansible_default_ipv4.interface)

So I had to change the line in defaults-fix.yml to
```
    line: 'INTERFACESv4="{{ dhcp_interfaces | default(ansible_default_ipv4.interface) }}"'
```
This should fallback to the current solution, but allows to define a variable dhcp_interfaces to override the default.

**Comment by lunarthegrey** [comment]
+1 on this. Running into the same issue.

**Comment by frock81** [comment]
I made a pull request that I believe will address the issue: https://github.com/bertvv/ansible-role-dhcp/pull/42

**Comment by blofeldthefish** [comment]
This functionality has now been merged into the master branch....
