### ISSUE TITLE
Package name changed in RHEL/Centos 8

### ISSUE THREAD

**Issue by dclairac** [bertvv/ansible-role-dhcp#40]
In RHEL/Centos 8, package name is now dhcp-server.

It could be possible to change task/mains.yml to have:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ default }}.yml"

And file with the good package name in it. 
  - RedHat-8.yml

But it could be easier to allow override (  use this loading system only if package_name variable not set).

**Comment by blofeldthefish** [comment]
The easiest way to achieve this would be in the vars/RedHat.yml file:

change:
dhcp_packages:
  - dhcp

to
dhcp_packages:
  - "{{ ( ansible_distribution_major_version == '8' ) | ternary( 'dhcp-server', 'dhcp' ) }}"

This is the minimal work required to address this change with respect to RHEL/CentOS 8.

Note: I have not tested the rest of the role, to ensure that it will function identically with RH8....

Feel free to look into incorporating this into a future PR!

**Comment by blofeldthefish** [comment]
This has been addressed by PR #44
