### ISSUE TITLE
captive portal options

### ISSUE THREAD

**Issue by damo2929** [bertvv/ansible-role-dhcp#66]
Hi thanks for the role
am trying to work out how to add options to support captive portals as described in RFC dated dec 2020

the options needed are.

option captive-portal code 114 = string;
option captive-portal "http://www.example.com/captive";

**Comment by bertvv** [comment]
Unfortunately, I do not have the resources to implement feature requests. A recent PR (#63) adds custom options, though, I think that may be a solution for you.
